[package]
name = "kbinxml"
version = "0.12.0"
authors = ["Matt Bilker <me@mbilker.us>"]

[dependencies]
byteorder = "1.2.3"
bytes = "0.4.10"
cfg-if = "0.1"
encoding = "0.2"
failure = "0.1.1"
indexmap = "1.0.1"
lazy_static = "1.0.0"
log = "0.4.1"
minidom = "0.9.0"
pretty_env_logger = "0.2.3"
quick-xml = "0.12.1"
rustc-hex = "2.0.1"

serde = { version = "1.0.69", optional = true }
serde_bytes = { version = "0.10.4", optional = true }
serde_derive = { version = "1.0.69", optional = true }

[features]
serde-1 = ["serde", "serde_bytes", "serde_derive", "indexmap/serde-1"]
