[package]
name = "kbinxml"
version = "0.3.0"
authors = ["Matt Bilker <me@mbilker.us>"]

[dependencies]
byteorder = "1.2.3"
encoding = "0.2"
failure = "0.1.1"
lazy_static = "1.0.0"
log = "0.4.1"
minidom = "0.9.0"
num = "0.1.42"
pretty_env_logger = "0.2.3"
quick-xml = "0.12.1"
rustc-hex = "1.0.0"
serde = "1.0.69"
serde_derive = "1.0.69"
