[package]
name = "psmap"
version = "1.2.0"
authors = ["Matt Bilker <me@mbilker.us>"]
license = "MIT"
edition = "2018"

[dependencies]
kbinxml = { path = "../kbinxml" }
psmap_derive = { path = "../psmap_derive" }
thiserror = "1.0.9"
